import type {
  Assertion,
  AssetGitRef,
  Environment,
  EnvironmentVariableOverride,
  EnvPriorityRef,
  ExecutionPlan,
  Folder,
  GlobalFileAsset,
  LinkedSnapshot,
  LinkedWorkspace,
  MockServer,
  Request as ApiRequest,
  RequestOverride,
  ReleaseHistory,
  ReleaseVersion,
  SecretCryptoMeta,
  SecretKeyMeta,
  WorkspaceLocal,
  WorkspaceSnapshotTrigger,
  WorkspaceSynced,
} from '@apicircle/shared';
import type { ParsedApicircleFolderExport } from '../import/apicircleFolder';

// =============================================================================
// WorkspacePatch — discriminated union of every mutation kind.
//
// A single value of this type completely describes a write to the workspace.
// `applyMutation(state, patch)` is the one place where these are dispatched;
// the UI store, MCP tool handlers, and CLI commands all funnel through it so
// semantics never drift between front-ends.
//
// Patches that target the synced document (`request.*`, `folder.*`,
// `environment.*`, `assertion.*`, `mock.*`) bump `synced.meta.updatedAt`.
// Patches that target the local document (`plan.*`) leave synced untouched.
// =============================================================================

export type WorkspacePatch =
  // ----- Requests (synced.collections.requests + tree) ----------------------
  | { kind: 'request.create'; request: ApiRequest }
  | { kind: 'request.update'; id: string; patch: Partial<Omit<ApiRequest, 'id' | 'createdAt'>> }
  | { kind: 'request.delete'; id: string }
  // ----- Folders (synced.collections.folders + tree) ------------------------
  | { kind: 'folder.create'; folder: Folder }
  | { kind: 'folder.delete'; id: string }
  | { kind: 'folder.move'; id: string; newParentId: string | null }
  // Patches editable folder fields (name + folder-level auth). Identity
  // (`id`, `parentId`) is immutable here — moves go through `folder.move`.
  // Semantics use key-presence: a key that is NOT in `patch` leaves the
  // existing field untouched; `auth: undefined` explicitly clears the
  // folder-level auth (so `inherit` requests fall through to the next
  // ancestor). Name uniqueness is enforced against siblings under the same
  // parent — a colliding rename no-ops the patch.
  | { kind: 'folder.update'; id: string; patch: Partial<Pick<Folder, 'name' | 'auth'>> }
  // Bulk import of a parsed `apicircle.folder/v1` envelope. Wraps every
  // descendant folder/request/dependency in a single atomic mutation so
  // headless writers (CLI / MCP) get the same name-uniquify + dependency
  // dedupe semantics the UI store uses.
  | {
      kind: 'folder.import_apicircle';
      parsed: ParsedApicircleFolderExport;
      parentFolderId: string | null;
    }
  // ----- Environments (synced.environments) ---------------------------------
  | { kind: 'environment.upsert'; environment: Environment }
  | { kind: 'environment.delete'; name: string }
  | { kind: 'environment.setActive'; name: string | null }
  | { kind: 'environment.setPriority'; order: EnvPriorityRef[] }
  // ----- Secret-vault slot metadata (synced.secretKeys) ---------------------
  // Headless writers (MCP environment.import on a v2 envelope, CLI tools)
  // mint slot metadata when the import carries a ciphertext + salt the
  // destination doesn't yet have. The slot's plaintext VALUE is per-device
  // and lives in local.secretIndex — that's intentionally NOT part of this
  // patch, so the missing-slots gate fires on the receiver until the user
  // provides the value. Eagerly merges by id; later upserts overwrite the
  // label + salt (a deliberate choice — a re-import with a different salt
  // signals key rotation).
  | { kind: 'secretKey.upsert'; meta: SecretKeyMeta }
  // ----- Secret-vault passphrase crypto (synced.secretCrypto) ---------------
  // Set when a user first establishes the workspace passphrase. The blob
  // (kdf/salt/iterations/verifier) is generated by `initSecretCrypto` in
  // `@apicircle/core/secrets/passphraseKey`; this patch is the
  // applyMutation-routed way to persist it so MCP / CLI / VS Code can all
  // bootstrap the same workspace. The plaintext passphrase never crosses
  // the bridge — only the derived key blob.
  //
  // `clear` is a recovery hatch for "I forgot the passphrase and accept
  // losing every encrypted variable" — wipes `secretCrypto`. Callers MUST
  // re-encrypt or drop encrypted env variables alongside this patch; this
  // mutation does not touch `environments[*].variables`.
  | { kind: 'secret.crypto.set'; crypto: SecretCryptoMeta }
  | { kind: 'secret.crypto.clear' }
  // ----- Assertions (slot of a Request) -------------------------------------
  | { kind: 'assertion.upsert'; requestId: string; assertion: Assertion }
  | { kind: 'assertion.delete'; requestId: string; assertionId: string }
  // ----- Mock servers (synced.mockServers) ----------------------------------
  | { kind: 'mock.upsert'; mock: MockServer }
  | { kind: 'mock.delete'; id: string }
  // ----- Releases (synced.releases.self) ------------------------------------
  // The workspace-self release ledger that linked consumers pin to.
  // `publish` carries a fully-built `ReleaseVersion`: the SHA-256
  // `workspaceSnapshot` is computed asynchronously by the caller via
  // `buildReleaseEntry`, so the reducer (and `applyMutation`) stay pure +
  // synchronous. `deprecate` (soft) / `yank` (hard) flip the signal flags on
  // an existing version. Unlike most reducers these THROW on a bad input
  // (invalid semver, duplicate, unknown version) rather than no-op silently —
  // publishing is a deliberate single action, never batched, so surfacing the
  // error to the command / MCP caller is the right contract.
  | { kind: 'release.publish'; entry: ReleaseVersion }
  | { kind: 'release.deprecate'; version: string }
  | { kind: 'release.yank'; version: string }
  // ----- Linked workspaces (synced.linkedWorkspaces + releases.perLink +
  //       local.linkedCollections) ------------------------------------------
  // A workspace this one consumes (private session-bound or public
  // marketplace), one level deep. `upsert` carries the full LinkedWorkspace
  // record plus the OPTIONAL cached release ledger (→ synced.releases.perLink)
  // and OPTIONAL collections/environments snapshot (→ local.linkedCollections).
  // The network fetch that produces the ledger + snapshot happens in the
  // command/host BEFORE this (pure, sync) patch — same split as
  // `release.publish` + `buildReleaseEntry`. Config-only edits (pin version,
  // scope, session mode, required keys, marketplace metadata) upsert the link
  // alone. `remove` cascades: it drops the link, its cached ledger, every
  // linkedOverride keyed `${id}:…`, the local snapshot, and any per-link
  // dedicated session entry.
  | {
      kind: 'linkedWorkspace.upsert';
      link: LinkedWorkspace;
      ledger?: ReleaseHistory;
      snapshot?: LinkedSnapshot;
    }
  | { kind: 'linkedWorkspace.remove'; id: string }
  // Atomic result of a three-way update (the consumer bumps to a newer source
  // version). Carries the freshly-resolved snapshot + ledger + the surviving
  // overrides for the link. Replaces this link's slice of every affected map;
  // other links are untouched. Produced by `applyLinkedUpdate` in the host.
  | {
      kind: 'linkedWorkspace.applyUpdate';
      id: string;
      pinnedVersion: string | null;
      snapshot: LinkedSnapshot;
      ledger: ReleaseHistory;
      requestOverrides: RequestOverride[];
      envVarOverrides: EnvironmentVariableOverride[];
    }
  // ----- Linked-content overrides (synced.linkedOverrides) -------------------
  // Consumer-side edits to a linked workspace's requests / env-vars, stored as
  // field-level deltas keyed `${linkedWorkspaceId}:${itemId}` (requests) and
  // `${linkedWorkspaceId}:${envName}:${varKey}` (env-vars). `set*` upserts one
  // delta; `remove*` drops one (reset to source); `clearForLink` discards all
  // of a link's mods at once.
  | { kind: 'linkedOverride.setRequest'; override: RequestOverride }
  | { kind: 'linkedOverride.removeRequest'; linkedWorkspaceId: string; itemId: string }
  | { kind: 'linkedOverride.setEnvVar'; override: EnvironmentVariableOverride }
  | {
      kind: 'linkedOverride.removeEnvVar';
      linkedWorkspaceId: string;
      envName: string;
      varKey: string;
    }
  | { kind: 'linkedOverride.clearForLink'; linkedWorkspaceId: string }
  // ----- Global file assets (synced.globalAssets.files) ---------------------
  // Asset provenance state machine. `upsertFile` and `removeFile` are the
  // CRUD primitives; the four `mark*` / `cleanup*` / `invalidateRef` kinds
  // are the state-machine transitions driven by push + refresh. See
  // docs/architecture/platform.md for the lifecycle table.
  | { kind: 'globalAsset.upsertFile'; file: GlobalFileAsset }
  | { kind: 'globalAsset.removeFile'; id: string }
  // Push flow: stamp the asset with the working-branch ref after the
  // commit lands. `ref.blobSha` is what makes the cleanup invariant
  // possible — without it we can't compare across refs.
  | { kind: 'globalAsset.markPushed'; id: string; ref: AssetGitRef }
  // Refresh-time promotion: the verification probe found the asset's
  // slot on the base branch (typically `main`), so the PR has merged.
  | { kind: 'globalAsset.markMerged'; id: string; ref: AssetGitRef }
  // Cleanup invariant: both refs resolved to the same blob → the
  // working ref is redundant. Drop it so the base ref is the single
  // source of truth.
  | { kind: 'globalAsset.cleanupWorkingRef'; id: string }
  // 404 on a verification probe → the ref no longer points at a real
  // blob. Drop it so reads stop trying that ref first.
  | { kind: 'globalAsset.invalidateRef'; id: string; which: 'working' | 'base' }
  // ----- Execution plans (local.executionPlans) -----------------------------
  | { kind: 'plan.upsert'; plan: ExecutionPlan }
  | { kind: 'plan.delete'; id: string }
  // ----- History (local.history.requestRuns + planRuns) ---------------------
  | { kind: 'history.delete_run'; runId: string }
  | { kind: 'history.delete_plan_run'; planRunId: string }
  | { kind: 'history.purge'; olderThanMs: number }
  // ----- Workspace snapshots (local.snapshots) ------------------------------
  | { kind: 'snapshot.capture'; trigger: WorkspaceSnapshotTrigger; note?: string; id?: string }
  | { kind: 'snapshot.delete'; id: string }
  | { kind: 'snapshot.restore'; id: string }
  | { kind: 'snapshot.set_max_bytes'; maxBytes: number };

export type WorkspacePatchKind = WorkspacePatch['kind'];

// Convenience alias for callers that want to hold a paired view of the
// workspace before passing it through `applyMutation`.
export interface WorkspaceState {
  synced: WorkspaceSynced;
  local: WorkspaceLocal;
}
