import type { McpToolName } from '@apicircle/shared';
import type { AnyToolDef } from './types';
import {
  importCurlTool,
  importOpenApiTool,
  importPostmanTool,
  importInsomniaTool,
  importHarTool,
} from './imports';
import { generateCodeTool } from './codegen';
import { workspaceListTool } from './workspaceList';
import {
  workspaceReadTool,
  workspaceWriteTool,
  requestCreateTool,
  requestReadTool,
  requestUpdateTool,
  requestDeleteTool,
  folderCreateTool,
  folderReadTool,
  folderUpdateTool,
  folderDeleteTool,
  environmentCreateTool,
  environmentReadTool,
  environmentUpdateTool,
  environmentDeleteTool,
  environmentSetActiveTool,
  environmentSetPriorityTool,
  environmentExportTool,
  environmentImportTool,
  planCreateTool,
  planReadTool,
  planUpdateTool,
  planDeleteTool,
  planRunTool,
  planAddStepTool,
  planRemoveStepTool,
  planReorderStepsTool,
  planSetVariablesTool,
  assertionCreateTool,
  assertionReadTool,
  assertionUpdateTool,
  assertionDeleteTool,
} from './crud';
import { folderExportJsonTool, folderImportJsonTool } from './folderExchange';
import {
  historyListRunsTool,
  historyGetRunTool,
  historyDeleteRunTool,
  historyPurgeTool,
} from './history';
import { codebaseExtractCollectionTool } from './codebase';
import {
  promptCreateEnvironmentTool,
  promptCreateAssertionTool,
  promptCreatePlanTool,
  promptCreateRequestTool,
  promptUpdateRequestTool,
  promptCreateFolderTreeTool,
  promptAddPlanStepsTool,
  promptSetPlanVariablesTool,
  promptCreateMockServerTool,
  promptAddMockEndpointTool,
  promptSetEndpointValidationRulesTool,
  promptSetEndpointResponseRulesTool,
  promptSetEndpointMultipliersTool,
} from './prompt';
import {
  mockCreateFromOpenApiTool,
  mockCreateFromPostmanTool,
  mockCreateFromInsomniaTool,
  mockCreateManualTool,
  mockListTool,
  mockListEndpointsTool,
  mockStartTool,
  mockStopTool,
  mockDeleteTool,
  mockAddEndpointTool,
  mockUpdateEndpointTool,
  mockDeleteEndpointTool,
  mockSetValidationRulesTool,
  mockSetResponseRulesTool,
  mockSetMultipliersTool,
  mockImportPostmanMockCollectionTool,
} from './mocks';

// Order matches MCP_TOOL_NAMES in `@apicircle/shared/src/mcp.ts`. CI guards
// drift via the registry test which asserts every catalog entry resolves.
export const TOOL_REGISTRY: AnyToolDef[] = [
  importCurlTool,
  importOpenApiTool,
  importPostmanTool,
  importInsomniaTool,
  importHarTool,
  generateCodeTool,
  workspaceListTool,
  workspaceReadTool,
  workspaceWriteTool,
  requestCreateTool,
  requestReadTool,
  requestUpdateTool,
  requestDeleteTool,
  folderCreateTool,
  folderReadTool,
  folderUpdateTool,
  folderDeleteTool,
  folderExportJsonTool,
  folderImportJsonTool,
  environmentCreateTool,
  environmentReadTool,
  environmentUpdateTool,
  environmentDeleteTool,
  environmentSetActiveTool,
  environmentSetPriorityTool,
  environmentExportTool,
  environmentImportTool,
  planCreateTool,
  planRunTool,
  planReadTool,
  planUpdateTool,
  planDeleteTool,
  planAddStepTool,
  planRemoveStepTool,
  planReorderStepsTool,
  planSetVariablesTool,
  assertionCreateTool,
  assertionReadTool,
  assertionUpdateTool,
  assertionDeleteTool,
  historyListRunsTool,
  historyGetRunTool,
  historyDeleteRunTool,
  historyPurgeTool,
  codebaseExtractCollectionTool,
  promptCreateEnvironmentTool,
  promptCreateAssertionTool,
  promptCreatePlanTool,
  promptCreateRequestTool,
  promptUpdateRequestTool,
  promptCreateFolderTreeTool,
  promptAddPlanStepsTool,
  promptSetPlanVariablesTool,
  promptCreateMockServerTool,
  promptAddMockEndpointTool,
  promptSetEndpointValidationRulesTool,
  promptSetEndpointResponseRulesTool,
  promptSetEndpointMultipliersTool,
  mockCreateFromOpenApiTool,
  mockCreateFromPostmanTool,
  mockCreateFromInsomniaTool,
  mockCreateManualTool,
  mockListTool,
  mockListEndpointsTool,
  mockStartTool,
  mockStopTool,
  mockDeleteTool,
  mockAddEndpointTool,
  mockUpdateEndpointTool,
  mockDeleteEndpointTool,
  mockSetValidationRulesTool,
  mockSetResponseRulesTool,
  mockSetMultipliersTool,
  mockImportPostmanMockCollectionTool,
];

export function getTool(name: McpToolName): AnyToolDef | undefined {
  return TOOL_REGISTRY.find((t) => t.name === name);
}
