// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: CC. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapCC: Readonly<Record<string, TcId>> = {
  'Concurrency :: Concurrency: Concurrent edits': 'TC-CC-0018',
  'Concurrency :: Concurrency: Delete the request being sent': 'TC-CC-0015',
  'Concurrency :: Concurrency: Edit during plan run': 'TC-CC-0019',
  'Concurrency :: Concurrency: Edit while running': 'TC-CC-0023',
  'Concurrency :: Concurrency: Mid-typing variable change': 'TC-CC-0020',
  'Concurrency :: Concurrency: Pull with unsaved': 'TC-CC-0021',
  'Concurrency :: Concurrency: Push during request': 'TC-CC-0016',
  'Concurrency :: Concurrency: Same workspace two tabs': 'TC-CC-0022',
  'Concurrency :: Concurrency: Sequential push/pull': 'TC-CC-0017',
  'Concurrency :: Concurrency: Switch mid-flight': 'TC-CC-0014',
  'Concurrency :: Concurrency: Two requests in flight': 'TC-CC-0013',
  Confirm: 'TC-CC-0004',
  DnD: 'TC-CC-0007',
  'Empty States :: Empty history': 'TC-CC-0011',
  'Empty States :: Empty mocks': 'TC-CC-0012',
  'Empty States :: Empty workspace CTA': 'TC-CC-0010',
  'Error Recovery': 'TC-CC-0009',
  'Modal :: Backdrop click does not close destructive': 'TC-CC-0006',
  'Modal :: Esc closes non-critical': 'TC-CC-0005',
  'Panel State :: Open Editor panel while: Empty workspace': 'TC-CC-0030',
  'Panel State :: Open Editor panel while: Loaded workspace with data': 'TC-CC-0031',
  'Panel State :: Open Editor panel while: Workspace mid-pull': 'TC-CC-0033',
  'Panel State :: Open Editor panel while: Workspace with active edits': 'TC-CC-0032',
  'Panel State :: Open Editor panel while: Workspace with conflict modal open': 'TC-CC-0034',
  'Panel State :: Open Editor panel while: Workspace with secrets locked (no passphrase)':
    'TC-CC-0035',
  'Panel State :: Open Environments panel while: Empty workspace': 'TC-CC-0036',
  'Panel State :: Open Environments panel while: Loaded workspace with data': 'TC-CC-0037',
  'Panel State :: Open Environments panel while: Workspace mid-pull': 'TC-CC-0039',
  'Panel State :: Open Environments panel while: Workspace with active edits': 'TC-CC-0038',
  'Panel State :: Open Environments panel while: Workspace with conflict modal open': 'TC-CC-0040',
  'Panel State :: Open Environments panel while: Workspace with secrets locked (no passphrase)':
    'TC-CC-0041',
  'Panel State :: Open Execution panel while: Empty workspace': 'TC-CC-0042',
  'Panel State :: Open Execution panel while: Loaded workspace with data': 'TC-CC-0043',
  'Panel State :: Open Execution panel while: Workspace mid-pull': 'TC-CC-0045',
  'Panel State :: Open Execution panel while: Workspace with active edits': 'TC-CC-0044',
  'Panel State :: Open Execution panel while: Workspace with conflict modal open': 'TC-CC-0046',
  'Panel State :: Open Execution panel while: Workspace with secrets locked (no passphrase)':
    'TC-CC-0047',
  'Panel State :: Open Help panel while: Empty workspace': 'TC-CC-0060',
  'Panel State :: Open Help panel while: Loaded workspace with data': 'TC-CC-0061',
  'Panel State :: Open Help panel while: Workspace mid-pull': 'TC-CC-0063',
  'Panel State :: Open Help panel while: Workspace with active edits': 'TC-CC-0062',
  'Panel State :: Open Help panel while: Workspace with conflict modal open': 'TC-CC-0064',
  'Panel State :: Open Help panel while: Workspace with secrets locked (no passphrase)':
    'TC-CC-0065',
  'Panel State :: Open History panel while: Empty workspace': 'TC-CC-0054',
  'Panel State :: Open History panel while: Loaded workspace with data': 'TC-CC-0055',
  'Panel State :: Open History panel while: Workspace mid-pull': 'TC-CC-0057',
  'Panel State :: Open History panel while: Workspace with active edits': 'TC-CC-0056',
  'Panel State :: Open History panel while: Workspace with conflict modal open': 'TC-CC-0058',
  'Panel State :: Open History panel while: Workspace with secrets locked (no passphrase)':
    'TC-CC-0059',
  'Panel State :: Open MCP panel while: Empty workspace': 'TC-CC-0066',
  'Panel State :: Open MCP panel while: Loaded workspace with data': 'TC-CC-0067',
  'Panel State :: Open MCP panel while: Workspace mid-pull': 'TC-CC-0069',
  'Panel State :: Open MCP panel while: Workspace with active edits': 'TC-CC-0068',
  'Panel State :: Open MCP panel while: Workspace with conflict modal open': 'TC-CC-0070',
  'Panel State :: Open MCP panel while: Workspace with secrets locked (no passphrase)':
    'TC-CC-0071',
  'Panel State :: Open Mocks panel while: Empty workspace': 'TC-CC-0048',
  'Panel State :: Open Mocks panel while: Loaded workspace with data': 'TC-CC-0049',
  'Panel State :: Open Mocks panel while: Workspace mid-pull': 'TC-CC-0051',
  'Panel State :: Open Mocks panel while: Workspace with active edits': 'TC-CC-0050',
  'Panel State :: Open Mocks panel while: Workspace with conflict modal open': 'TC-CC-0052',
  'Panel State :: Open Mocks panel while: Workspace with secrets locked (no passphrase)':
    'TC-CC-0053',
  'Panel State :: Open Workspace panel while: Empty workspace': 'TC-CC-0024',
  'Panel State :: Open Workspace panel while: Loaded workspace with data': 'TC-CC-0025',
  'Panel State :: Open Workspace panel while: Workspace mid-pull': 'TC-CC-0027',
  'Panel State :: Open Workspace panel while: Workspace with active edits': 'TC-CC-0026',
  'Panel State :: Open Workspace panel while: Workspace with conflict modal open': 'TC-CC-0028',
  'Panel State :: Open Workspace panel while: Workspace with secrets locked (no passphrase)':
    'TC-CC-0029',
  Persistence: 'TC-CC-0008',
  'Toasts :: Error toast on network failure': 'TC-CC-0002',
  'Toasts :: Stacked dismiss independently': 'TC-CC-0003',
  'Toasts :: Success toast on push': 'TC-CC-0001',
};
