// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: DC. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapDC: Readonly<Record<string, TcId>> = {
  External: 'TC-DC-0004',
  'Help :: Markdown XSS safe': 'TC-DC-0002',
  'Help :: Search topic': 'TC-DC-0001',
  'Request Docs': 'TC-DC-0003',
};
