// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: PE. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapPE: Readonly<Record<string, TcId>> = {
  'Boundaries :: Stress: Body 100MB raw text': 'TC-PE-0018',
  'Boundaries :: Stress: History with 5000 runs': 'TC-PE-0020',
  'Boundaries :: Stress: Mock server with 200 endpoints': 'TC-PE-0014',
  'Boundaries :: Stress: Plan with 100 steps': 'TC-PE-0015',
  'Boundaries :: Stress: Request name with 500 chars': 'TC-PE-0024',
  'Boundaries :: Stress: Request with 50 headers': 'TC-PE-0016',
  'Boundaries :: Stress: Request with 50 query params': 'TC-PE-0017',
  'Boundaries :: Stress: Response 100MB binary': 'TC-PE-0019',
  'Boundaries :: Stress: URL with 16KB length': 'TC-PE-0025',
  'Boundaries :: Stress: Unicode-heavy workspace (all names CJK)': 'TC-PE-0022',
  'Boundaries :: Stress: Very deep folder nesting (20 levels)': 'TC-PE-0023',
  'Boundaries :: Stress: Workspace with 10 mock servers': 'TC-PE-0013',
  'Boundaries :: Stress: Workspace with 100 collections': 'TC-PE-0009',
  'Boundaries :: Stress: Workspace with 100 environment vars': 'TC-PE-0012',
  'Boundaries :: Stress: Workspace with 1000 history runs and switch': 'TC-PE-0021',
  'Boundaries :: Stress: Workspace with 10000 requests': 'TC-PE-0008',
  'Boundaries :: Stress: Workspace with 50 environments': 'TC-PE-0011',
  'Boundaries :: Stress: Workspace with 500 folders': 'TC-PE-0010',
  Debounce: 'TC-PE-0005',
  'Large Response': 'TC-PE-0002',
  'Large Workspace': 'TC-PE-0001',
  'Many Attachments': 'TC-PE-0004',
  'Many Vars': 'TC-PE-0003',
  'Tree Render': 'TC-PE-0007',
  'Workspace Switch': 'TC-PE-0006',
};
