// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: HS. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapHS: Readonly<Record<string, TcId>> = {
  Buckets: 'TC-HS-0002',
  Clear: 'TC-HS-0009',
  Delete: 'TC-HS-0008',
  'Filter :: Date-range filter': 'TC-HS-0006',
  'Filter :: Filter URL substring': 'TC-HS-0005',
  'Filter :: Filter by method': 'TC-HS-0004',
  'Filter :: Filter status range': 'TC-HS-0003',
  Log: 'TC-HS-0001',
  Performance: 'TC-HS-0011',
  Persistence: 'TC-HS-0010',
  Replay: 'TC-HS-0007',
};
