// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: WB. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapWB: Readonly<Record<string, TcId>> = {
  Bookmark: 'TC-WB-0015',
  'Browser Back': 'TC-WB-0014',
  'Browser Compat :: Smoke Edge': 'TC-WB-0009',
  'Browser Compat :: Smoke Firefox': 'TC-WB-0007',
  'Browser Compat :: Smoke Safari': 'TC-WB-0008',
  'Browser Compat :: Smoke test Chrome': 'TC-WB-0006',
  'Clipboard :: Clipboard denied non-secure': 'TC-WB-0018',
  'Clipboard :: Copy cURL via Clipboard API': 'TC-WB-0017',
  DevTools: 'TC-WB-0016',
  'Inactive Tab': 'TC-WB-0022',
  'Mixed Content': 'TC-WB-0013',
  'Multi-Tab :: Two tabs editing same request': 'TC-WB-0002',
  'Multi-Tab :: Two tabs same workspace': 'TC-WB-0001',
  PWA: 'TC-WB-0024',
  Permissions: 'TC-WB-0023',
  Popup: 'TC-WB-0019',
  'Privacy Mode': 'TC-WB-0010',
  Quota: 'TC-WB-0011',
  'Refresh :: F5 preserves body input': 'TC-WB-0004',
  'Refresh :: Hard reload preserves IDB': 'TC-WB-0005',
  'Service Worker': 'TC-WB-0012',
  'Storage Events': 'TC-WB-0021',
  'Tab Close': 'TC-WB-0003',
  'Third-Party Cookies': 'TC-WB-0020',
  'URL Scheme': 'TC-WB-0025',
  Visibility: 'TC-WB-0027',
  'Vite Proxy': 'TC-WB-0026',
};
