// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: HD. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapHD: Readonly<Record<string, TcId>> = {
  'Case insensitivity': 'TC-HD-0018',
  'Content-Length auto-computed for body': 'TC-HD-0028',
  'Content-Type from body type': 'TC-HD-0029',
  'Cookie header from jar vs manual': 'TC-HD-0031',
  'Duplicate header keys': 'TC-HD-0019',
  'Empty value': 'TC-HD-0020',
  'Header autocomplete suggests': 'TC-HD-0027',
  'Header disabled': 'TC-HD-0026',
  'Header name with non-ASCII': 'TC-HD-0033',
  'Header name with space': 'TC-HD-0034',
  'Header order preserved': 'TC-HD-0036',
  'Header overrides auth-managed': 'TC-HD-0025',
  'Header value with non-ASCII': 'TC-HD-0032',
  'Header value with semicolon': 'TC-HD-0035',
  'Newline in value (CRLF injection)': 'TC-HD-0022',
  'Null byte in header': 'TC-HD-0023',
  "Standard :: Send standard header 'Accept'": 'TC-HD-0001',
  "Standard :: Send standard header 'Accept-Encoding'": 'TC-HD-0002',
  "Standard :: Send standard header 'Accept-Language'": 'TC-HD-0003',
  "Standard :: Send standard header 'Authorization'": 'TC-HD-0004',
  "Standard :: Send standard header 'Cache-Control'": 'TC-HD-0005',
  "Standard :: Send standard header 'Connection'": 'TC-HD-0017',
  "Standard :: Send standard header 'Content-Length'": 'TC-HD-0007',
  "Standard :: Send standard header 'Content-Type'": 'TC-HD-0006',
  "Standard :: Send standard header 'Cookie'": 'TC-HD-0008',
  "Standard :: Send standard header 'If-Match'": 'TC-HD-0013',
  "Standard :: Send standard header 'If-Modified-Since'": 'TC-HD-0015',
  "Standard :: Send standard header 'If-None-Match'": 'TC-HD-0014',
  "Standard :: Send standard header 'Origin'": 'TC-HD-0009',
  "Standard :: Send standard header 'Range'": 'TC-HD-0016',
  "Standard :: Send standard header 'Referer'": 'TC-HD-0010',
  "Standard :: Send standard header 'User-Agent'": 'TC-HD-0011',
  "Standard :: Send standard header 'X-Forwarded-For'": 'TC-HD-0012',
  'User-set Content-Type overrides': 'TC-HD-0030',
  'Variable in header key': 'TC-HD-0038',
  'Variable in header value': 'TC-HD-0037',
  'Very long header value (8KB)': 'TC-HD-0024',
  'Whitespace value': 'TC-HD-0021',
};
