// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: SY. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapSY: Readonly<Record<string, TcId>> = {
  CSP: 'TC-SY-0008',
  'Code Signing': 'TC-SY-0010',
  Headers: 'TC-SY-0007',
  Iframe: 'TC-SY-0009',
  Imports: 'TC-SY-0005',
  'Secrets :: Console redacts secrets': 'TC-SY-0004',
  'Secrets :: Secrets not in plaintext history': 'TC-SY-0003',
  URL: 'TC-SY-0006',
  'XSS :: HTML preview sandboxed': 'TC-SY-0001',
  'XSS :: Variable values not HTML-interpreted': 'TC-SY-0002',
};
