// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: BE. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapBE: Readonly<Record<string, TcId>> = {
  Binary: 'TC-BE-0016',
  'File Upload :: Browser file picker': 'TC-BE-0022',
  'File Upload :: Drag-drop from OS': 'TC-BE-0023',
  'Form Data :: Empty value row': 'TC-BE-0006',
  'Form Data :: Multiple files in same row': 'TC-BE-0005',
  'Form Data :: Submit text field': 'TC-BE-0002',
  'Form Data :: Unicode field name': 'TC-BE-0007',
  'Form Data :: Upload 50MB file': 'TC-BE-0004',
  'Form Data :: Upload file row': 'TC-BE-0003',
  'GraphQL :: Fragments and directives': 'TC-BE-0020',
  'GraphQL :: Mutation operation': 'TC-BE-0019',
  'GraphQL :: Send GraphQL query': 'TC-BE-0017',
  'GraphQL :: Variables sent': 'TC-BE-0018',
  'Raw HTML': 'TC-BE-0014',
  'Raw JSON :: Invalid JSON shows squiggle': 'TC-BE-0011',
  'Raw JSON :: JSON schema validates body': 'TC-BE-0012',
  'Raw JSON :: Submit JSON body': 'TC-BE-0010',
  'Raw Text': 'TC-BE-0015',
  'Raw XML': 'TC-BE-0013',
  Type: 'TC-BE-0001',
  'Type Switch': 'TC-BE-0021',
  'URL-encoded :: Reserved chars encoded': 'TC-BE-0009',
  'URL-encoded :: Submit urlencoded': 'TC-BE-0008',
};
