// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: MK. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapMK: Readonly<Record<string, TcId>> = {
  Definition: 'TC-MK-0001',
  Delete: 'TC-MK-0006',
  Duplicate: 'TC-MK-0007',
  'Endpoint :: :id and {id} both supported': 'TC-MK-0003',
  'Endpoint :: Add GET /users/:id': 'TC-MK-0002',
  'Logs :: Large log buffer caps memory': 'TC-MK-0017',
  'Logs :: Request logs in panel': 'TC-MK-0016',
  Rename: 'TC-MK-0008',
  Response: 'TC-MK-0004',
  'Runtime :: Export CLI command': 'TC-MK-0010',
  'Runtime :: Multiple mocks concurrently': 'TC-MK-0012',
  'Runtime :: Port conflict cycles': 'TC-MK-0013',
  'Runtime :: Quit stops all mocks': 'TC-MK-0014',
  'Runtime :: Renderer reload preserves mocks': 'TC-MK-0015',
  'Runtime :: Start disabled on web': 'TC-MK-0009',
  'Runtime :: Stop mock': 'TC-MK-0011',
  'Spec Import': 'TC-MK-0005',
};
