// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: SE. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapSE: Readonly<Record<string, TcId>> = {
  'Marketplace :: Empty results': 'TC-SE-0003',
  'Marketplace :: Link public workspace': 'TC-SE-0002',
  'Marketplace :: Search public workspaces': 'TC-SE-0001',
};
