// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: NW. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapNW: Readonly<Record<string, TcId>> = {
  'CORS Preflight': 'TC-NW-0009',
  Connection: 'TC-NW-0004',
  DNS: 'TC-NW-0003',
  Offline: 'TC-NW-0010',
  'Redirect :: Follow 302': 'TC-NW-0006',
  'Redirect :: Redirect loop terminated': 'TC-NW-0007',
  Slow: 'TC-NW-0002',
  Streaming: 'TC-NW-0008',
  TLS: 'TC-NW-0005',
  Timeout: 'TC-NW-0001',
};
