// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: OI. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapOI: Readonly<Record<string, TcId>> = {
  'AWS Cognito :: OAuth2 against AWS Cognito using authorization_code': 'TC-OI-0037',
  'AWS Cognito :: OAuth2 against AWS Cognito using authorization_code+PKCE': 'TC-OI-0038',
  'AWS Cognito :: OAuth2 against AWS Cognito using client_credentials': 'TC-OI-0036',
  'AWS Cognito :: OAuth2 against AWS Cognito using device_code': 'TC-OI-0040',
  'AWS Cognito :: OAuth2 against AWS Cognito using implicit': 'TC-OI-0042',
  'AWS Cognito :: OAuth2 against AWS Cognito using password': 'TC-OI-0039',
  'AWS Cognito :: OAuth2 against AWS Cognito using refresh_token': 'TC-OI-0041',
  'Auth0 :: OAuth2 against Auth0 using authorization_code': 'TC-OI-0002',
  'Auth0 :: OAuth2 against Auth0 using authorization_code+PKCE': 'TC-OI-0003',
  'Auth0 :: OAuth2 against Auth0 using client_credentials': 'TC-OI-0001',
  'Auth0 :: OAuth2 against Auth0 using device_code': 'TC-OI-0005',
  'Auth0 :: OAuth2 against Auth0 using implicit': 'TC-OI-0007',
  'Auth0 :: OAuth2 against Auth0 using password': 'TC-OI-0004',
  'Auth0 :: OAuth2 against Auth0 using refresh_token': 'TC-OI-0006',
  'Firebase Auth :: OAuth2 against Firebase Auth using authorization_code': 'TC-OI-0051',
  'Firebase Auth :: OAuth2 against Firebase Auth using authorization_code+PKCE': 'TC-OI-0052',
  'Firebase Auth :: OAuth2 against Firebase Auth using client_credentials': 'TC-OI-0050',
  'Firebase Auth :: OAuth2 against Firebase Auth using device_code': 'TC-OI-0054',
  'Firebase Auth :: OAuth2 against Firebase Auth using implicit': 'TC-OI-0056',
  'Firebase Auth :: OAuth2 against Firebase Auth using password': 'TC-OI-0053',
  'Firebase Auth :: OAuth2 against Firebase Auth using refresh_token': 'TC-OI-0055',
  'Generic OIDC :: OAuth2 against Generic OIDC using authorization_code': 'TC-OI-0065',
  'Generic OIDC :: OAuth2 against Generic OIDC using authorization_code+PKCE': 'TC-OI-0066',
  'Generic OIDC :: OAuth2 against Generic OIDC using client_credentials': 'TC-OI-0064',
  'Generic OIDC :: OAuth2 against Generic OIDC using device_code': 'TC-OI-0068',
  'Generic OIDC :: OAuth2 against Generic OIDC using implicit': 'TC-OI-0070',
  'Generic OIDC :: OAuth2 against Generic OIDC using password': 'TC-OI-0067',
  'Generic OIDC :: OAuth2 against Generic OIDC using refresh_token': 'TC-OI-0069',
  'GitHub :: OAuth2 against GitHub using authorization_code': 'TC-OI-0023',
  'GitHub :: OAuth2 against GitHub using authorization_code+PKCE': 'TC-OI-0024',
  'GitHub :: OAuth2 against GitHub using client_credentials': 'TC-OI-0022',
  'GitHub :: OAuth2 against GitHub using device_code': 'TC-OI-0026',
  'GitHub :: OAuth2 against GitHub using implicit': 'TC-OI-0028',
  'GitHub :: OAuth2 against GitHub using password': 'TC-OI-0025',
  'GitHub :: OAuth2 against GitHub using refresh_token': 'TC-OI-0027',
  'Google Identity :: OAuth2 against Google Identity using authorization_code': 'TC-OI-0016',
  'Google Identity :: OAuth2 against Google Identity using authorization_code+PKCE': 'TC-OI-0017',
  'Google Identity :: OAuth2 against Google Identity using client_credentials': 'TC-OI-0015',
  'Google Identity :: OAuth2 against Google Identity using device_code': 'TC-OI-0019',
  'Google Identity :: OAuth2 against Google Identity using implicit': 'TC-OI-0021',
  'Google Identity :: OAuth2 against Google Identity using password': 'TC-OI-0018',
  'Google Identity :: OAuth2 against Google Identity using refresh_token': 'TC-OI-0020',
  'Keycloak :: OAuth2 against Keycloak using authorization_code': 'TC-OI-0044',
  'Keycloak :: OAuth2 against Keycloak using authorization_code+PKCE': 'TC-OI-0045',
  'Keycloak :: OAuth2 against Keycloak using client_credentials': 'TC-OI-0043',
  'Keycloak :: OAuth2 against Keycloak using device_code': 'TC-OI-0047',
  'Keycloak :: OAuth2 against Keycloak using implicit': 'TC-OI-0049',
  'Keycloak :: OAuth2 against Keycloak using password': 'TC-OI-0046',
  'Keycloak :: OAuth2 against Keycloak using refresh_token': 'TC-OI-0048',
  'Microsoft Identity (Entra) :: OAuth2 against Microsoft Identity (Entra) using authorization_code':
    'TC-OI-0030',
  'Microsoft Identity (Entra) :: OAuth2 against Microsoft Identity (Entra) using authorization_code+PKCE':
    'TC-OI-0031',
  'Microsoft Identity (Entra) :: OAuth2 against Microsoft Identity (Entra) using client_credentials':
    'TC-OI-0029',
  'Microsoft Identity (Entra) :: OAuth2 against Microsoft Identity (Entra) using device_code':
    'TC-OI-0033',
  'Microsoft Identity (Entra) :: OAuth2 against Microsoft Identity (Entra) using implicit':
    'TC-OI-0035',
  'Microsoft Identity (Entra) :: OAuth2 against Microsoft Identity (Entra) using password':
    'TC-OI-0032',
  'Microsoft Identity (Entra) :: OAuth2 against Microsoft Identity (Entra) using refresh_token':
    'TC-OI-0034',
  'Okta :: OAuth2 against Okta using authorization_code': 'TC-OI-0009',
  'Okta :: OAuth2 against Okta using authorization_code+PKCE': 'TC-OI-0010',
  'Okta :: OAuth2 against Okta using client_credentials': 'TC-OI-0008',
  'Okta :: OAuth2 against Okta using device_code': 'TC-OI-0012',
  'Okta :: OAuth2 against Okta using implicit': 'TC-OI-0014',
  'Okta :: OAuth2 against Okta using password': 'TC-OI-0011',
  'Okta :: OAuth2 against Okta using refresh_token': 'TC-OI-0013',
  'PingFederate :: OAuth2 against PingFederate using authorization_code': 'TC-OI-0058',
  'PingFederate :: OAuth2 against PingFederate using authorization_code+PKCE': 'TC-OI-0059',
  'PingFederate :: OAuth2 against PingFederate using client_credentials': 'TC-OI-0057',
  'PingFederate :: OAuth2 against PingFederate using device_code': 'TC-OI-0061',
  'PingFederate :: OAuth2 against PingFederate using implicit': 'TC-OI-0063',
  'PingFederate :: OAuth2 against PingFederate using password': 'TC-OI-0060',
  'PingFederate :: OAuth2 against PingFederate using refresh_token': 'TC-OI-0062',
};
