// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: CR. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapCR: Readonly<Record<string, TcId>> = {
  'Collection :: Create collection at root': 'TC-CR-0001',
  'Collection :: Delete collection cascades to children': 'TC-CR-0005',
  'Collection :: Delete empty collection': 'TC-CR-0004',
  'Collection :: Duplicate collection deep-copies tree': 'TC-CR-0006',
  'Collection :: Duplicate name at same level': 'TC-CR-0003',
  'Collection :: Rename collection inline': 'TC-CR-0002',
  'Delete Safety :: Active env fallback': 'TC-CR-0036',
  'Delete Safety :: Cascade deletes children': 'TC-CR-0034',
  'Delete Safety :: Full cascade': 'TC-CR-0035',
  'Delete Safety :: Other endpoints unaffected': 'TC-CR-0040',
  'Delete Safety :: Overrides become orphaned': 'TC-CR-0037',
  'Delete Safety :: Overrides removed': 'TC-CR-0042',
  'Delete Safety :: Plan handles missing step': 'TC-CR-0033',
  'Delete Safety :: Refs resolve empty': 'TC-CR-0038',
  'Delete Safety :: Schema ref orphaned': 'TC-CR-0039',
  'Delete Safety :: Secret references break': 'TC-CR-0043',
  'Delete Safety :: Stop runtime first or warn': 'TC-CR-0041',
  'Folder :: 5-level nesting': 'TC-CR-0008',
  'Folder :: Create folder under collection': 'TC-CR-0007',
  'Folder :: Folder auth inherited by requests': 'TC-CR-0009',
  Move: 'TC-CR-0018',
  'Reference Safety :: Active env resolution still works': 'TC-CR-0024',
  'Reference Safety :: Child request paths/IDs unchanged': 'TC-CR-0021',
  'Reference Safety :: Children intact': 'TC-CR-0023',
  'Reference Safety :: Encrypted bytes unchanged': 'TC-CR-0031',
  'Reference Safety :: Endpoints inside intact': 'TC-CR-0028',
  'Reference Safety :: Existing {{var}} refs need updating': 'TC-CR-0026',
  'Reference Safety :: Folder-level auth still inherited': 'TC-CR-0022',
  'Reference Safety :: History entries display old or current name consistently': 'TC-CR-0020',
  'Reference Safety :: Linked env priority entry retained': 'TC-CR-0025',
  'Reference Safety :: Overrides keyed by id intact': 'TC-CR-0032',
  'Reference Safety :: Plan run history retained': 'TC-CR-0027',
  'Reference Safety :: Plan steps referencing request still resolve': 'TC-CR-0019',
  'Reference Safety :: Selector rules still apply': 'TC-CR-0029',
  'Reference Safety :: bodySchemaId refs update': 'TC-CR-0030',
  'Reorder :: Drag folder into descendant blocked': 'TC-CR-0015',
  'Reorder :: Drag request between folders': 'TC-CR-0013',
  'Reorder :: Reorder within folder': 'TC-CR-0014',
  'Request :: Create via Ctrl+N': 'TC-CR-0010',
  'Request :: Delete keeps history readable': 'TC-CR-0012',
  'Request :: Duplicate clones all fields': 'TC-CR-0011',
  'Search :: Filter tree by substring': 'TC-CR-0016',
  'Search :: Search is case-insensitive': 'TC-CR-0017',
};
