// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: TP. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapTP: Readonly<Record<string, TcId>> = {
  'Anonymous install id': 'TC-TP-0006',
  'Crash reports include stack but no user data': 'TC-TP-0005',
  'Crash reports opt-in': 'TC-TP-0004',
  'Disable telemetry from settings': 'TC-TP-0002',
  'Event payload contains no PII': 'TC-TP-0003',
  'Network for telemetry only when enabled': 'TC-TP-0008',
  'Privacy policy link visible': 'TC-TP-0009',
  'Reset install id': 'TC-TP-0007',
  'Telemetry default off (or first-run consent)': 'TC-TP-0001',
  'Workspace data never sent to telemetry endpoint': 'TC-TP-0010',
};
