// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: CA. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapCA: Readonly<Record<string, TcId>> = {
  '304 with no body shown correctly': 'TC-CA-0010',
  'Cache-Control: no-store respected': 'TC-CA-0003',
  'Cache-Control: private vs public': 'TC-CA-0004',
  'Disable cache per request': 'TC-CA-0011',
  'ETag changes on body change': 'TC-CA-0006',
  'Expires header old (HTTP/1.0)': 'TC-CA-0009',
  'If-Match for optimistic concurrency': 'TC-CA-0007',
  'If-Modified-Since': 'TC-CA-0002',
  'If-None-Match with stored ETag': 'TC-CA-0001',
  'Stale-while-revalidate (if respected)': 'TC-CA-0008',
  'Vary header tracked': 'TC-CA-0005',
};
