// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: BK. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapBK: Readonly<Record<string, TcId>> = {
  'Backup before destructive op (rest workspace, delete)': 'TC-BK-0006',
  'Backup encrypted with passphrase': 'TC-BK-0010',
  'Backup file integrity check (checksum)': 'TC-BK-0011',
  'Cross-version backup compatibility': 'TC-BK-0012',
  'Disk full during export': 'TC-BK-0008',
  'Export does not include history (local-only)': 'TC-BK-0003',
  'Export full workspace JSON (synced)': 'TC-BK-0001',
  'Export includes attachments (or references)': 'TC-BK-0002',
  'Import into existing workspace merges vs overwrites': 'TC-BK-0005',
  'Re-import exported workspace creates equivalent state': 'TC-BK-0004',
  'Restore from auto-snapshot': 'TC-BK-0007',
  'Selective restore: only environments': 'TC-BK-0009',
};
