// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: O2. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapO2: Readonly<Record<string, TcId>> = {
  'Auth Code': 'TC-O2-0020',
  'Auto-Refresh': 'TC-O2-0006',
  BroadcastChannel: 'TC-O2-0017',
  'Callback Page': 'TC-O2-0023',
  Clear: 'TC-O2-0007',
  'Client Credentials': 'TC-O2-0001',
  'Cross-Origin': 'TC-O2-0019',
  'Device Code': 'TC-O2-0003',
  Error: 'TC-O2-0014',
  Implicit: 'TC-O2-0021',
  Multiple: 'TC-O2-0022',
  PKCE: 'TC-O2-0004',
  Password: 'TC-O2-0002',
  'Popup :: Auth code via popup': 'TC-O2-0015',
  'Popup :: Popup blocked': 'TC-O2-0016',
  'Private Key JWT': 'TC-O2-0010',
  'Redirect URI': 'TC-O2-0009',
  Refresh: 'TC-O2-0005',
  Scope: 'TC-O2-0011',
  State: 'TC-O2-0008',
  'Token Display :: Expiry countdown': 'TC-O2-0013',
  'Token Display :: Token masked': 'TC-O2-0012',
  postMessage: 'TC-O2-0018',
};
