// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: GT. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapGT: Readonly<Record<string, TcId>> = {
  'Branch :: Switch with unsaved warns': 'TC-GT-0006',
  'Branch :: Switch working branch': 'TC-GT-0005',
  'Commit Author': 'TC-GT-0008',
  'Commit Msg': 'TC-GT-0012',
  'GitHub Flow :: GitHub flow: Branch protection requires status checks': 'TC-GT-0027',
  'GitHub Flow :: GitHub flow: Concurrent push from two devices': 'TC-GT-0034',
  'GitHub Flow :: GitHub flow: Direct push to main by collaborator': 'TC-GT-0032',
  'GitHub Flow :: GitHub flow: Force-push on working branch': 'TC-GT-0033',
  'GitHub Flow :: GitHub flow: Link to archived repo': 'TC-GT-0021',
  'GitHub Flow :: GitHub flow: Link to forked repo (upstream PR)': 'TC-GT-0022',
  'GitHub Flow :: GitHub flow: Link to org repo (member, read-only)': 'TC-GT-0017',
  'GitHub Flow :: GitHub flow: Link to org repo (member, write)': 'TC-GT-0016',
  'GitHub Flow :: GitHub flow: Link to org repo (non-member, private)': 'TC-GT-0019',
  'GitHub Flow :: GitHub flow: Link to org repo (non-member, public)': 'TC-GT-0018',
  'GitHub Flow :: GitHub flow: Link to private repo with personal token': 'TC-GT-0015',
  'GitHub Flow :: GitHub flow: Link to public repo': 'TC-GT-0014',
  'GitHub Flow :: GitHub flow: Link to repo with branch protection': 'TC-GT-0020',
  'GitHub Flow :: GitHub flow: Network drops during pull': 'TC-GT-0037',
  'GitHub Flow :: GitHub flow: Network drops during push (large)': 'TC-GT-0036',
  'GitHub Flow :: GitHub flow: OAuth scope downgrade after linking': 'TC-GT-0023',
  'GitHub Flow :: GitHub flow: OAuth token revoked on github.com mid-session': 'TC-GT-0035',
  'GitHub Flow :: GitHub flow: Open PR shows in workspace UI': 'TC-GT-0040',
  'GitHub Flow :: GitHub flow: PR merged via merge commit': 'TC-GT-0031',
  'GitHub Flow :: GitHub flow: PR merged via rebase on GitHub': 'TC-GT-0030',
  'GitHub Flow :: GitHub flow: PR merged via squash on GitHub': 'TC-GT-0029',
  'GitHub Flow :: GitHub flow: Push of conflict resolution': 'TC-GT-0039',
  'GitHub Flow :: GitHub flow: Push to branch with PR draft': 'TC-GT-0028',
  'GitHub Flow :: GitHub flow: Repo deleted after linking': 'TC-GT-0024',
  'GitHub Flow :: GitHub flow: Repo renamed by owner': 'TC-GT-0025',
  'GitHub Flow :: GitHub flow: Repo transferred to another owner': 'TC-GT-0026',
  'GitHub Flow :: GitHub flow: Workspace push includes secrets metadata only (not values)':
    'TC-GT-0038',
  Network: 'TC-GT-0009',
  'PR Capability': 'TC-GT-0010',
  'Pull Race': 'TC-GT-0011',
  Push: 'TC-GT-0001',
  'Push Conflict': 'TC-GT-0002',
  Rebase: 'TC-GT-0013',
  Retired: 'TC-GT-0007',
  'Three-way :: Auto-merge non-conflicting': 'TC-GT-0003',
  'Three-way :: Conflict surfaces resolution UI': 'TC-GT-0004',
};
