// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: MU. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapMU: Readonly<Record<string, TcId>> = {
  'Branch protection requires linear history': 'TC-MU-0008',
  'Dev A deletes; dev B edits': 'TC-MU-0004',
  'Dev forgets to pull and pushes after main moved': 'TC-MU-0006',
  'Different secret slots per user (named)': 'TC-MU-0015',
  'Encrypted vars on multi-user repo': 'TC-MU-0013',
  'Encrypted vars unlocked on one device, locked on other': 'TC-MU-0014',
  'Force-push by another dev': 'TC-MU-0010',
  'Linked workspace owned by another team updates': 'TC-MU-0012',
  'PR review on GitHub (out-of-band edit)': 'TC-MU-0007',
  'Pull while another push in progress on remote': 'TC-MU-0011',
  'Three devs in succession': 'TC-MU-0005',
  'Two devs add request to same folder simultaneously': 'TC-MU-0001',
  'Two devs edit different fields of same request': 'TC-MU-0002',
  'Two devs edit same field of same request': 'TC-MU-0003',
  'Two devs on different branches, then merge': 'TC-MU-0009',
};
