// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: CE. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapCE: Readonly<Record<string, TcId>> = {
  'Failure :: Corrupt gzip response': 'TC-CE-0017',
  'Failure :: Unsupported encoding from server': 'TC-CE-0018',
  'Negotiation :: Accept-Encoding: Accept-Encoding: *': 'TC-CE-0015',
  'Negotiation :: Accept-Encoding: Accept-Encoding: gzip': 'TC-CE-0013',
  'Negotiation :: Accept-Encoding: Accept-Encoding: gzip, br;q=0.8': 'TC-CE-0014',
  'Negotiation :: Accept-Encoding: No Accept-Encoding header': 'TC-CE-0016',
  'br (Brotli) :: Compression: Request - br (Brotli)': 'TC-CE-0005',
  'br (Brotli) :: Compression: Response - br (Brotli)': 'TC-CE-0006',
  'deflate :: Compression: Request - deflate': 'TC-CE-0003',
  'deflate :: Compression: Response - deflate': 'TC-CE-0004',
  'gzip :: Compression: Request - gzip': 'TC-CE-0001',
  'gzip :: Compression: Response - gzip': 'TC-CE-0002',
  'gzip+chained :: Compression: Request - gzip+chained': 'TC-CE-0011',
  'gzip+chained :: Compression: Response - gzip+chained': 'TC-CE-0012',
  'identity (none) :: Compression: Request - identity (none)': 'TC-CE-0009',
  'identity (none) :: Compression: Response - identity (none)': 'TC-CE-0010',
  'zstd :: Compression: Request - zstd': 'TC-CE-0007',
  'zstd :: Compression: Response - zstd': 'TC-CE-0008',
};
