// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: HV. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapHV: Readonly<Record<string, TcId>> = {
  'Alt-Svc upgrade': 'TC-HV-0008',
  'Connection close mid-response': 'TC-HV-0010',
  'HTTP/1.0': 'TC-HV-0001',
  'HTTP/1.1 100-Continue': 'TC-HV-0009',
  'HTTP/1.1 Transfer-Encoding chunked': 'TC-HV-0003',
  'HTTP/1.1 keepalive': 'TC-HV-0002',
  'HTTP/1.1 pipelining (if supported)': 'TC-HV-0011',
  'HTTP/2 header compression (HPACK)': 'TC-HV-0005',
  'HTTP/2 multiplexed': 'TC-HV-0004',
  'HTTP/2 server push (if used)': 'TC-HV-0006',
  'HTTP/3 (QUIC)': 'TC-HV-0007',
  'Keep-Alive with idle timeout': 'TC-HV-0012',
  'Response without Content-Length and without chunked': 'TC-HV-0013',
  'Trailer headers (HTTP/1.1)': 'TC-HV-0014',
};
