// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: WS. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapWS: Readonly<Record<string, TcId>> = {
  'Browser Nav': 'TC-WS-0032',
  'Create :: 256-char name truncation/rejection': 'TC-WS-0004',
  'Create :: Create new local workspace': 'TC-WS-0001',
  'Create :: Duplicate workspace name allowed (UUID id)': 'TC-WS-0006',
  'Create :: Reject blank name': 'TC-WS-0002',
  'Create :: Unicode + emoji name': 'TC-WS-0003',
  'Create :: Whitespace-only name rejected': 'TC-WS-0005',
  'Cross-Tab Sync': 'TC-WS-0033',
  'Delete :: Confirm deletion removes from registry': 'TC-WS-0011',
  'Delete :: Delete requires confirmation': 'TC-WS-0010',
  'Hydrate :: Passphrase prompt on workspace with secrets': 'TC-WS-0023',
  'Hydrate :: Skip passphrase keeps non-secret data usable': 'TC-WS-0025',
  'Hydrate :: Wrong passphrase keeps secrets locked': 'TC-WS-0024',
  'Link to Git :: Link to repo without write permission': 'TC-WS-0015',
  'Link to Git :: Link unlinked workspace to GitHub repo': 'TC-WS-0012',
  'Link to Git :: OAuth scope denial blocks linking': 'TC-WS-0013',
  'Link to Git :: Token revoked surfaces re-auth prompt': 'TC-WS-0014',
  'Multi-Tab': 'TC-WS-0027',
  Offline: 'TC-WS-0022',
  Pull: 'TC-WS-0019',
  'Push :: Push during offline shows clear error': 'TC-WS-0018',
  'Push :: Push edits to working branch': 'TC-WS-0016',
  'Push :: Push with no changes is no-op': 'TC-WS-0017',
  Quota: 'TC-WS-0030',
  'Refresh :: Browser refresh preserves workspace state': 'TC-WS-0028',
  'Refresh :: Refresh detects retired branch': 'TC-WS-0020',
  'Refresh :: Refresh during in-flight request': 'TC-WS-0029',
  Reset: 'TC-WS-0021',
  Restore: 'TC-WS-0026',
  Storage: 'TC-WS-0031',
  'Switcher :: Recent list shows last-active first': 'TC-WS-0009',
  'Switcher :: Recent workspaces persist across restart': 'TC-WS-0008',
  'Switcher :: Switch between two workspaces': 'TC-WS-0007',
};
