// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: GQ. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapGQ: Readonly<Record<string, TcId>> = {
  Completions: 'TC-GQ-0002',
  Errors: 'TC-GQ-0007',
  'Introspect :: Fetch schema': 'TC-GQ-0001',
  'Introspect :: Introspection disabled': 'TC-GQ-0005',
  'Multi-Operation': 'TC-GQ-0006',
  'Schema Reuse': 'TC-GQ-0004',
  Variables: 'TC-GQ-0003',
};
