// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: LO. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapLO: Readonly<Record<string, TcId>> = {
  'Strings :: All visible UI strings translatable': 'TC-LO-0027',
  'Strings :: Long translation strings (German)': 'TC-LO-0029',
  'Strings :: Missing translation falls back to English': 'TC-LO-0028',
  'ar-EG :: Locale ar-EG - RTL layout': 'TC-LO-0017',
  'ar-EG :: Locale ar-EG - date/time format': 'TC-LO-0015',
  'ar-EG :: Locale ar-EG - number format': 'TC-LO-0016',
  'de-DE :: Locale de-DE - date/time format': 'TC-LO-0005',
  'de-DE :: Locale de-DE - number format': 'TC-LO-0006',
  'en-GB :: Locale en-GB - date/time format': 'TC-LO-0003',
  'en-GB :: Locale en-GB - number format': 'TC-LO-0004',
  'en-US :: Locale en-US - date/time format': 'TC-LO-0001',
  'en-US :: Locale en-US - number format': 'TC-LO-0002',
  'es-ES :: Locale es-ES - date/time format': 'TC-LO-0011',
  'es-ES :: Locale es-ES - number format': 'TC-LO-0012',
  'fr-FR :: Locale fr-FR - date/time format': 'TC-LO-0009',
  'fr-FR :: Locale fr-FR - number format': 'TC-LO-0010',
  'he-IL :: Locale he-IL - RTL layout': 'TC-LO-0020',
  'he-IL :: Locale he-IL - date/time format': 'TC-LO-0018',
  'he-IL :: Locale he-IL - number format': 'TC-LO-0019',
  'ja-JP :: Locale ja-JP - date/time format': 'TC-LO-0007',
  'ja-JP :: Locale ja-JP - number format': 'TC-LO-0008',
  'ko-KR :: Locale ko-KR - date/time format': 'TC-LO-0023',
  'ko-KR :: Locale ko-KR - number format': 'TC-LO-0024',
  'pt-BR :: Locale pt-BR - date/time format': 'TC-LO-0021',
  'pt-BR :: Locale pt-BR - number format': 'TC-LO-0022',
  'ru-RU :: Locale ru-RU - date/time format': 'TC-LO-0025',
  'ru-RU :: Locale ru-RU - number format': 'TC-LO-0026',
  'zh-CN :: Locale zh-CN - date/time format': 'TC-LO-0013',
  'zh-CN :: Locale zh-CN - number format': 'TC-LO-0014',
};
