// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: DS. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapDS: Readonly<Record<string, TcId>> = {
  'App Quit :: Alt+F4': 'TC-DS-0015',
  'App Quit :: Cmd+Q': 'TC-DS-0014',
  'Auto-Update :: Check Now button': 'TC-DS-0003',
  'Auto-Update :: Check offline': 'TC-DS-0004',
  'Auto-Update :: Check on startup': 'TC-DS-0001',
  'Auto-Update :: Signature failure aborts': 'TC-DS-0005',
  'Auto-Update :: Update banner': 'TC-DS-0002',
  'Code Signing :: Windows SmartScreen': 'TC-DS-0020',
  'Code Signing :: macOS Gatekeeper': 'TC-DS-0019',
  Crash: 'TC-DS-0029',
  'First Run': 'TC-DS-0028',
  'IPC Security': 'TC-DS-0022',
  Linux: 'TC-DS-0021',
  'MCP Bridge :: Config snippet copy': 'TC-DS-0026',
  'MCP Bridge :: Per-OS path shown': 'TC-DS-0027',
  'Mock Manager': 'TC-DS-0025',
  'Native Menu :: Edit menu Cut/Copy/Paste/Undo/Redo': 'TC-DS-0007',
  'Native Menu :: File menu items work': 'TC-DS-0006',
  'Native Menu :: Help About/Docs/Report': 'TC-DS-0010',
  'Native Menu :: View Reload/DevTools/Zoom': 'TC-DS-0008',
  'Native Menu :: Window Minimize/Zoom/Close': 'TC-DS-0009',
  'Native Secret :: First write prompts keychain': 'TC-DS-0023',
  'Native Secret :: Keychain unavailable fallback': 'TC-DS-0024',
  Network: 'TC-DS-0031',
  Power: 'TC-DS-0030',
  'Single Instance': 'TC-DS-0018',
  Storage: 'TC-DS-0032',
  Window: 'TC-DS-0033',
  'Window State :: Bounds persist': 'TC-DS-0011',
  'Window State :: Fullscreen persists': 'TC-DS-0013',
  'Window State :: Monitor disconnect clamps': 'TC-DS-0012',
  'macOS Dock': 'TC-DS-0016',
  'macOS Menu Bar': 'TC-DS-0017',
};
