// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: WK. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapWK: Readonly<Record<string, TcId>> = {
  'SSE connect': 'TC-WK-0013',
  'SSE event with id and reconnect': 'TC-WK-0014',
  'SSE multiline data': 'TC-WK-0015',
  'WS auth via cookie': 'TC-WK-0008',
  'WS auth via header on upgrade': 'TC-WK-0007',
  'WS auto-reconnect on drop': 'TC-WK-0009',
  'WS close 1000 vs 1006': 'TC-WK-0010',
  'WS connect to ws://': 'TC-WK-0001',
  'WS connect to wss://': 'TC-WK-0002',
  'WS history persisted': 'TC-WK-0012',
  'WS large frame (1MB)': 'TC-WK-0011',
  'WS receive server-pushed frames': 'TC-WK-0005',
  'WS send binary frame': 'TC-WK-0004',
  'WS send text frame': 'TC-WK-0003',
  'WS subprotocol negotiation': 'TC-WK-0006',
  'gRPC bidirectional': 'TC-WK-0019',
  'gRPC client streaming': 'TC-WK-0018',
  'gRPC over TLS': 'TC-WK-0021',
  'gRPC reflection': 'TC-WK-0020',
  'gRPC server streaming': 'TC-WK-0017',
  'gRPC unary call (if supported)': 'TC-WK-0016',
};
