// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: VR. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapVR: Readonly<Record<string, TcId>> = {
  'Encryption :: Master JWK plaintext in IDB': 'TC-VR-0021',
  'Encryption :: Passphrase AES-GCM': 'TC-VR-0020',
  'Env :: Activate env': 'TC-VR-0002',
  'Env :: Create env': 'TC-VR-0001',
  'Env :: Delete env with confirm': 'TC-VR-0004',
  'Env :: Duplicate env': 'TC-VR-0003',
  'Env :: Rename env updates refs': 'TC-VR-0005',
  Keychain: 'TC-VR-0023',
  'Linked Env :: Consumer override': 'TC-VR-0019',
  'Linked Env :: Drag reorder priority': 'TC-VR-0018',
  Passphrase: 'TC-VR-0022',
  Resolution: 'TC-VR-0017',
  'Scope :: Linked env per priority': 'TC-VR-0016',
  'Scope :: Request context overrides env': 'TC-VR-0014',
  'Scope :: Workspace var fallback': 'TC-VR-0015',
  'Var :: Add plaintext var': 'TC-VR-0006',
  'Var :: Add secret var masked': 'TC-VR-0007',
  'Var :: Autocomplete in URL': 'TC-VR-0010',
  'Var :: Hyphen in name': 'TC-VR-0012',
  'Var :: Special chars in var name': 'TC-VR-0011',
  'Var :: Toggle plaintext->secret': 'TC-VR-0008',
  'Var :: Toggle secret->plaintext warns': 'TC-VR-0009',
  'Var :: Very long value (1MB)': 'TC-VR-0013',
};
