// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: KB. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapKB: Readonly<Record<string, TcId>> = {
  'Conflict :: Ctrl+F browser Find': 'TC-KB-0009',
  'Conflict :: Ctrl+P browser Print': 'TC-KB-0010',
  'Conflict :: Ctrl+R reloads browser': 'TC-KB-0007',
  'Conflict :: Ctrl+W closes tab': 'TC-KB-0008',
  'Font Size': 'TC-KB-0005',
  'New Request': 'TC-KB-0006',
  Panels: 'TC-KB-0002',
  Refresh: 'TC-KB-0004',
  Send: 'TC-KB-0001',
  Vault: 'TC-KB-0003',
};
