// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: OP. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapOP: Readonly<Record<string, TcId>> = {
  'Arch :: Keychain integration on Arch': 'TC-OP-0023',
  'Arch :: Smoke on Arch rolling': 'TC-OP-0022',
  'Arch :: Window state on Arch': 'TC-OP-0024',
  'Architecture :: ARM64 on Windows': 'TC-OP-0028',
  'Architecture :: Apple Silicon (arm64) on macOS': 'TC-OP-0025',
  'Architecture :: Intel (x86_64) on macOS': 'TC-OP-0026',
  'Architecture :: arm64 on Linux': 'TC-OP-0030',
  'Architecture :: x86_64 on Linux': 'TC-OP-0029',
  'Architecture :: x86_64 on Windows': 'TC-OP-0027',
  'Chrome canary :: Smoke Chrome canary on Mac': 'TC-OP-0004',
  'Chrome canary :: Smoke Chrome canary on Win': 'TC-OP-0005',
  'Chrome stable :: Smoke Chrome stable on Linux': 'TC-OP-0003',
  'Chrome stable :: Smoke Chrome stable on Mac': 'TC-OP-0001',
  'Chrome stable :: Smoke Chrome stable on Win': 'TC-OP-0002',
  'Edge stable :: Smoke Edge stable on Mac': 'TC-OP-0011',
  'Edge stable :: Smoke Edge stable on Win': 'TC-OP-0012',
  'Fedora 40 :: Keychain integration on Fedora 40': 'TC-OP-0020',
  'Fedora 40 :: Smoke on Fedora 40 ': 'TC-OP-0019',
  'Fedora 40 :: Window state on Fedora 40': 'TC-OP-0021',
  'Firefox ESR': 'TC-OP-0009',
  'Firefox stable :: Smoke Firefox stable on Linux': 'TC-OP-0008',
  'Firefox stable :: Smoke Firefox stable on Mac': 'TC-OP-0006',
  'Firefox stable :: Smoke Firefox stable on Win': 'TC-OP-0007',
  Safari: 'TC-OP-0010',
  'Ubuntu 22.04 :: Keychain integration on Ubuntu 22.04': 'TC-OP-0014',
  'Ubuntu 22.04 :: Smoke on Ubuntu 22.04 Jammy': 'TC-OP-0013',
  'Ubuntu 22.04 :: Window state on Ubuntu 22.04': 'TC-OP-0015',
  'Ubuntu 24.04 :: Keychain integration on Ubuntu 24.04': 'TC-OP-0017',
  'Ubuntu 24.04 :: Smoke on Ubuntu 24.04 Noble': 'TC-OP-0016',
  'Ubuntu 24.04 :: Window state on Ubuntu 24.04': 'TC-OP-0018',
};
