// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: AL. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapAL: Readonly<Record<string, TcId>> = {
  ARIA: 'TC-AL-0007',
  'Color Independence': 'TC-AL-0004',
  Contrast: 'TC-AL-0008',
  'Focus Ring': 'TC-AL-0002',
  'Keyboard Only': 'TC-AL-0006',
  'Reduced Motion': 'TC-AL-0005',
  'Screen Reader': 'TC-AL-0003',
  'Tab Order': 'TC-AL-0001',
};
