// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: SM. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapSM: Readonly<Record<string, TcId>> = {
  'CLI MCP version mismatch with desktop': 'TC-SM-0009',
  'Encrypted secrets survive migration': 'TC-SM-0011',
  'Linked workspace ledger migration': 'TC-SM-0012',
  'Migration adds new optional fields': 'TC-SM-0004',
  'Migration is reversible (or one-way clearly stated)': 'TC-SM-0007',
  'Migration removes a deprecated field': 'TC-SM-0006',
  'Migration renames a field': 'TC-SM-0005',
  'Open future-schema workspace.json': 'TC-SM-0003',
  'Open v1 workspace.json in current app': 'TC-SM-0001',
  'Open v2 workspace.json': 'TC-SM-0002',
  'Telemetry: migration event tracked once per upgrade': 'TC-SM-0010',
  'Two devices on different app versions': 'TC-SM-0008',
};
