// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: PR. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapPR: Readonly<Record<string, TcId>> = {
  'Proxy :: Proxy: Captive portal interception': 'TC-PR-0012',
  'Proxy :: Proxy: HTTPS proxy': 'TC-PR-0004',
  'Proxy :: Proxy: Manual HTTP proxy': 'TC-PR-0002',
  'Proxy :: Proxy: Manual SOCKS5 proxy': 'TC-PR-0003',
  'Proxy :: Proxy: Network change to/from proxy': 'TC-PR-0013',
  'Proxy :: Proxy: PAC file URL': 'TC-PR-0007',
  'Proxy :: Proxy: Per-request proxy override': 'TC-PR-0009',
  'Proxy :: Proxy: Proxy bypass list': 'TC-PR-0008',
  'Proxy :: Proxy: Proxy refuses connection': 'TC-PR-0011',
  'Proxy :: Proxy: Proxy unreachable': 'TC-PR-0010',
  'Proxy :: Proxy: Proxy with Basic auth': 'TC-PR-0005',
  'Proxy :: Proxy: Proxy with NTLM auth': 'TC-PR-0006',
  'Proxy :: Proxy: System proxy (OS-level)': 'TC-PR-0001',
};
