import * as http from 'node:http';
import * as crypto from 'node:crypto';
import {
  createMcpServer,
  InProcessMockController,
  StreamableHTTPServerTransport,
  type WorkspaceProvider,
} from '@apicircle/mcp-server';
import type { WorkspacePatch, WorkspaceState } from '@apicircle/core';
import type { WorkspaceSynced, WorkspaceLocal } from '@apicircle/shared';
import type { VsCodeBridge, WorkspaceSurface } from './vscodeBridge';

// =============================================================================
// Phase 10 — In-extension MCP Host over HTTP/Streamable.
//
// VS Code as BOTH host AND client of its own MCP catalog. Closes Phase 5+
// deferred item: today external AI clients launch the `apicircle-mcp`
// binary themselves (stdio); this host exposes the SAME 79-tool catalog
// over a local HTTP endpoint so clients can connect without spawning a
// subprocess. Same code path as the stdio server — only the transport
// changes.
//
// Security model (read carefully — the wrong default here is dangerous):
//
//   1. Bind ONLY to loopback. The default `bindHost` is `127.0.0.1`. The
//      setting validator refuses anything outside the loopback range
//      (`127.0.0.0/8`, `::1`). A misconfiguration that tries to bind
//      `0.0.0.0` is rejected at startup with a clear error toast.
//
//   2. Bearer-token auth on every request. Token is generated by
//      `crypto.randomBytes(32).toString('base64url')` at host start and
//      rotated on every restart. Missing / mismatched token → 401.
//
//   3. Host-header validation (DNS rebinding guard). We accept ONLY
//      `127.0.0.1[:port]`, `localhost[:port]`, and `[::1][:port]`. A
//      malicious page in the user's browser cannot forge `Host: evil.com`
//      and have us serve it as if it were localhost.
//
//   4. `apicircle.mcp.allowDecrypt` setting still gates secret-value
//      decryption (P5 contract). Embedded host doesn't relax this — the
//      tool catalog only sees decrypted values when the setting is on.
//
//   5. Off by default. The `apicircle.mcp.embeddedHost.enabled` setting
//      is `false` by default — users have to opt in.
//
// Lifecycle:
//
//   - `start()`: bind socket, attach MCP transport, return EmbeddedHostInfo.
//   - `stop()`: close transport + HTTP server. Idempotent.
//   - `restart()`: stop + start. Rotates the bearer token.
//
// Connection URL the user shares with their AI client (incl. token):
//
//   http://127.0.0.1:<port>/mcp?token=<base64url>
//
// Token can also travel via the standard `Authorization: Bearer <token>`
// header; the URL form is provided for clients that don't let you set
// headers (rare but it happens).
// =============================================================================

export const LOOPBACK_HOSTS = new Set(['127.0.0.1', 'localhost', '::1']);

export class UnsafeBindHostError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'UnsafeBindHostError';
  }
}

/**
 * Validate that the configured bindHost is a loopback address. Rejects
 * any value not in the loopback set + any IP outside the `127.0.0.0/8`
 * range. Mirrors the same pattern as P6's path-traversal guard.
 */
export function assertLoopbackBindHost(bindHost: string): string {
  // Strip surrounding brackets if it's an IPv6 literal in URL form.
  const normalized = bindHost
    .replace(/^\[|\]$/g, '')
    .toLowerCase()
    .trim();
  if (LOOPBACK_HOSTS.has(normalized)) return normalized;
  // Allow any 127.x.y.z (whole /8 block).
  if (/^127\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(normalized)) {
    const octets = normalized.split('.').map(Number);
    if (octets.every((n) => n >= 0 && n <= 255)) return normalized;
  }
  throw new UnsafeBindHostError(
    `apicircle.mcp.embeddedHost.bindHost must be a loopback address (127.0.0.1, localhost, ::1, or any 127.x.y.z). Refusing to bind ${bindHost} — binding to a non-loopback interface exposes the workspace's MCP tools to your network and is unsafe.`,
  );
}

export interface EmbeddedHostOptions {
  bridge: VsCodeBridge;
  /** Port to bind to. `0` = let the OS pick a free port. */
  port?: number;
  /** Bind host (must be loopback). Default `127.0.0.1`. */
  bindHost?: string;
  /** Server-info name sent to clients on handshake. */
  serverName?: string;
  /** Server-info version. */
  serverVersion?: string;
  log?: (msg: string) => void;
}

export interface EmbeddedHostInfo {
  port: number;
  bindHost: string;
  /** Bearer token for this session. Rotated on restart. */
  token: string;
  /** Full URL with the token embedded — what users paste into AI clients. */
  url: string;
}

interface RunningServer {
  http: http.Server;
  close: () => Promise<void>;
  info: EmbeddedHostInfo;
}

export class EmbeddedMcpHost {
  private running: RunningServer | null = null;
  private readonly log: (msg: string) => void;

  constructor(
    private readonly bridge: VsCodeBridge,
    log?: (msg: string) => void,
  ) {
    this.log = log ?? (() => undefined);
  }

  isRunning(): boolean {
    return this.running !== null;
  }

  info(): EmbeddedHostInfo | null {
    return this.running?.info ?? null;
  }

  async start(opts: Omit<EmbeddedHostOptions, 'bridge'> = {}): Promise<EmbeddedHostInfo> {
    if (this.running) {
      throw new Error('Embedded MCP host is already running. Call stop() or restart() first.');
    }
    const bindHost = assertLoopbackBindHost(opts.bindHost ?? '127.0.0.1');
    const port = opts.port ?? 0;
    const token = crypto.randomBytes(32).toString('base64url');

    // Build the WorkspaceProvider over the bridge.
    const workspaceProvider = new BridgeWorkspaceProvider(this.bridge);
    // Mock controller — reuses the same engine the desktop runs. The
    // embedded host doesn't manage mocks (those are owned by
    // VsCodeMockController); we pass an in-process one purely so the
    // mock.* tool calls don't crash. Real lifecycle stays with the
    // existing controller.
    const mockController = new InProcessMockController();

    const mcp = createMcpServer({
      workspace: workspaceProvider,
      mock: mockController,
      serverInfo: {
        name: opts.serverName ?? 'apicircle-embedded',
        version: opts.serverVersion ?? '0.0.0',
      },
    });

    // Streamable HTTP transport — MCP's modern HTTP-based transport,
    // supersedes the older raw-SSE shape and is what Copilot Chat /
    // newer Cursor builds expect.
    const transport = new StreamableHTTPServerTransport({
      sessionIdGenerator: () => crypto.randomUUID(),
    });
    await mcp.connect(transport);

    const server = http.createServer((req, res) => {
      this.handle(req, res, token, transport).catch((err) => {
        this.log(
          `embedded MCP request handler threw: ${err instanceof Error ? err.message : String(err)}`,
        );
        try {
          res.statusCode = 500;
          res.end('Internal Server Error');
        } catch {
          // ignore — response may have already ended
        }
      });
    });

    const boundPort = await new Promise<number>((resolve, reject) => {
      server.once('error', reject);
      server.listen(port, bindHost, () => {
        server.off('error', reject);
        const addr = server.address();
        if (addr && typeof addr === 'object') resolve(addr.port);
        else reject(new Error('server.address() returned an unexpected shape'));
      });
    });

    const info: EmbeddedHostInfo = {
      port: boundPort,
      bindHost,
      token,
      url: `http://${bindHost}:${boundPort}/mcp?token=${token}`,
    };
    this.log(`embedded MCP host listening on ${info.url}`);

    this.running = {
      http: server,
      info,
      close: async () => {
        await new Promise<void>((resolve) => server.close(() => resolve()));
        await transport.close();
        await mcp.close();
      },
    };
    return info;
  }

  async stop(): Promise<void> {
    if (!this.running) return;
    const r = this.running;
    this.running = null;
    try {
      await r.close();
      this.log(`embedded MCP host stopped (was on ${r.info.url})`);
    } catch (err) {
      this.log(`embedded MCP host stop threw: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  async restart(opts: Omit<EmbeddedHostOptions, 'bridge'> = {}): Promise<EmbeddedHostInfo> {
    await this.stop();
    return this.start(opts);
  }

  dispose(): void {
    void this.stop();
  }

  // ---------------------------------------------------------------------------
  // Request handler — auth + Host-header guard + delegate to MCP transport.
  // ---------------------------------------------------------------------------

  private async handle(
    req: http.IncomingMessage,
    res: http.ServerResponse,
    expectedToken: string,
    transport: {
      handleRequest: (
        req: http.IncomingMessage,
        res: http.ServerResponse,
        body?: unknown,
      ) => Promise<void>;
    },
  ): Promise<void> {
    // 1. Host-header validation (DNS rebinding guard).
    const hostHeader = req.headers.host ?? '';
    const hostname = hostHeader
      .replace(/:\d+$/, '')
      .replace(/^\[|\]$/g, '')
      .toLowerCase();
    if (!LOOPBACK_HOSTS.has(hostname) && !/^127\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(hostname)) {
      res.statusCode = 403;
      res.setHeader('Content-Type', 'application/json');
      res.end(JSON.stringify({ error: 'forbidden', reason: 'non-loopback Host header' }));
      this.log(`rejected request with Host=${hostHeader}`);
      return;
    }

    // 2. Bearer-token auth. Accept both `Authorization: Bearer <token>`
    //    and `?token=<token>` (for clients that can't set headers).
    //
    // Manual prefix match instead of `/^Bearer\s+(.+)$/i` so CodeQL doesn't
    // flag the `\s+` + `.+` pairing as a polynomial regex on a header value
    // sourced directly from the network.
    const auth = req.headers.authorization ?? '';
    const bearer = extractBearerToken(auth);
    const url = new URL(req.url ?? '/', `http://${hostHeader || 'localhost'}`);
    const queryToken = url.searchParams.get('token');
    const presented = bearer ?? queryToken ?? '';
    if (!safeEqual(presented, expectedToken)) {
      res.statusCode = 401;
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('WWW-Authenticate', 'Bearer realm="apicircle-mcp"');
      res.end(JSON.stringify({ error: 'unauthorized' }));
      return;
    }

    // 3. Route to MCP transport.
    if (url.pathname === '/mcp' || url.pathname === '/') {
      await transport.handleRequest(req, res);
      return;
    }
    res.statusCode = 404;
    res.end();
  }
}

/**
 * Parse `Authorization: Bearer <token>` without a regex. Trims any
 * whitespace between `Bearer` and the token, returns `undefined` if the
 * scheme isn't bearer or the token is empty.
 */
function extractBearerToken(auth: string): string | undefined {
  const prefix = 'bearer';
  if (auth.length <= prefix.length) return undefined;
  if (auth.slice(0, prefix.length).toLowerCase() !== prefix) return undefined;
  const after = auth.slice(prefix.length);
  // Require at least one whitespace between scheme and token.
  if (after.length === 0 || !/^\s/.test(after)) return undefined;
  const token = after.replace(/^\s+/, '');
  return token.length > 0 ? token : undefined;
}

/**
 * Constant-time comparison for bearer tokens. Prevents timing attacks on
 * the token validation path (even though the tokens are 256 bits of
 * random bytes — defence in depth).
 */
function safeEqual(a: string, b: string): boolean {
  const aBuf = Buffer.from(a);
  const bBuf = Buffer.from(b);
  if (aBuf.length !== bBuf.length) return false;
  return crypto.timingSafeEqual(aBuf, bBuf);
}

// ---------------------------------------------------------------------------
// Bridge-backed WorkspaceProvider
// ---------------------------------------------------------------------------

/**
 * Adapter between `VsCodeBridge.activeWorkspace()` and the MCP host's
 * `WorkspaceProvider` interface. Reads from / writes to the same surface
 * the editor commands use, so MCP tool calls see the exact in-memory state
 * the user just edited (no disk-snapshot lag).
 *
 * NOTE: if the user switches workspaces while a client is connected, the
 * provider follows the active workspace — by design. The MCP catalog
 * already supports multi-workspace addressing via `workspace.list` /
 * `workspace.setActive`; the embedded host inherits that.
 */
class BridgeWorkspaceProvider implements WorkspaceProvider {
  constructor(private readonly bridge: VsCodeBridge) {}

  private surface(): WorkspaceSurface {
    const active = this.bridge.activeWorkspace();
    if (!active) {
      throw new Error(
        'BridgeWorkspaceProvider: no active workspace. Open a folder containing .apicircle/workspace.json before invoking MCP tools.',
      );
    }
    return active;
  }

  read(): Promise<WorkspaceState> {
    return this.surface().read();
  }

  async apply(patch: WorkspacePatch): Promise<{ state: WorkspaceState; changedIds: string[] }> {
    const surface = this.surface();
    const result = await surface.apply(patch);
    const state = await surface.read();
    return {
      state,
      changedIds: result.changedIds ?? [],
    };
  }

  write(next: { synced?: WorkspaceSynced; local?: WorkspaceLocal }): Promise<WorkspaceState> {
    return this.surface().write(next);
  }
}
