// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: NS. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapNS: Readonly<Record<string, TcId>> = {
  'TLS :: TLS: Certificate transparency logs (CT)': 'TC-NS-0014',
  'TLS :: TLS: Cipher suite restrictions': 'TC-NS-0013',
  'TLS :: TLS: Custom CA cert uploaded': 'TC-NS-0009',
  'TLS :: TLS: DNS-over-HTTPS (DoH)': 'TC-NS-0015',
  'TLS :: TLS: Endpoint behind Cloudflare / WAF': 'TC-NS-0017',
  'TLS :: TLS: Endpoint with HSTS': 'TC-NS-0018',
  'TLS :: TLS: Expired cert': 'TC-NS-0003',
  'TLS :: TLS: Hostname mismatch (SNI)': 'TC-NS-0004',
  'TLS :: TLS: IPv6 endpoint': 'TC-NS-0016',
  "TLS :: TLS: Per-request 'allow insecure'": 'TC-NS-0010',
  'TLS :: TLS: Revoked cert (OCSP/CRL)': 'TC-NS-0005',
  'TLS :: TLS: Self-signed cert': 'TC-NS-0002',
  'TLS :: TLS: TLS 1.0 endpoint (deprecated)': 'TC-NS-0006',
  'TLS :: TLS: TLS 1.2 endpoint': 'TC-NS-0007',
  'TLS :: TLS: TLS 1.3 endpoint': 'TC-NS-0008',
  'TLS :: TLS: Valid HTTPS cert': 'TC-NS-0001',
  'TLS :: TLS: mTLS missing client cert': 'TC-NS-0012',
  'TLS :: TLS: mTLS with client cert': 'TC-NS-0011',
};
