// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: LV. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapLV: Readonly<Record<string, TcId>> = {
  'Adopt new version': 'TC-LV-0004',
  'Breaking change in new version (removed env var)': 'TC-LV-0006',
  'Compare diff between linked versions': 'TC-LV-0013',
  'Decline new version (stay pinned)': 'TC-LV-0005',
  'Link to latest version': 'TC-LV-0001',
  'Linked WS that itself links to another WS (chain)': 'TC-LV-0015',
  'Linked release ledger refresh': 'TC-LV-0012',
  'Multiple linked workspaces with conflicting var names': 'TC-LV-0008',
  'Override per linked-version': 'TC-LV-0009',
  'Pin to specific version': 'TC-LV-0002',
  'Release notes Markdown rendered': 'TC-LV-0014',
  'Renamed entity in new version': 'TC-LV-0007',
  'Source unpublished a version we pinned': 'TC-LV-0011',
  'Unlink preserves local copies (optional)': 'TC-LV-0010',
  'Update banner when source publishes new version': 'TC-LV-0003',
};
