// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: HR. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapHR: Readonly<Record<string, TcId>> = {
  'AWS SigV4 (timestamp sensitive)': 'TC-HR-0005',
  'Digest auth': 'TC-HR-0006',
  'OAuth2 Bearer (token may be expired)': 'TC-HR-0004',
  'POST with JSON body': 'TC-HR-0002',
  'POST with form-data + file attachment': 'TC-HR-0003',
  'Replay 100 runs in batch (if supported)': 'TC-HR-0012',
  'Replay GET response includes Set-Cookie': 'TC-HR-0015',
  'Replay GraphQL with stored schema': 'TC-HR-0014',
  'Replay aborted mid-flight': 'TC-HR-0017',
  'Replay across workspace switch': 'TC-HR-0009',
  'Replay against unreachable host': 'TC-HR-0018',
  'Replay creates new history entry': 'TC-HR-0011',
  'Replay run from before schema migration': 'TC-HR-0010',
  'Replay shows raw old response and new response side by side': 'TC-HR-0016',
  'Replay updates request UI to historical state': 'TC-HR-0019',
  'Replay with assertions runs them too': 'TC-HR-0013',
  'Request was deleted': 'TC-HR-0008',
  'Simple GET': 'TC-HR-0001',
  'Variable interpolation since env changed': 'TC-HR-0007',
};
