// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: WR. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapWR: Readonly<Record<string, TcId>> = {
  'Empty repo init': 'TC-WR-0024',
  'Large workspace (10MB JSON)': 'TC-WR-0028',
  'Repo with secrets references but no passphrase metadata': 'TC-WR-0027',
  'Round-trip: Active environment': 'TC-WR-0009',
  'Round-trip: Body schema reference': 'TC-WR-0006',
  'Round-trip: Collections and folders (tree)': 'TC-WR-0001',
  'Round-trip: Environment priority order': 'TC-WR-0008',
  'Round-trip: Environments and their variables': 'TC-WR-0007',
  'Round-trip: Execution plans': 'TC-WR-0011',
  'Round-trip: Global GraphQL docs': 'TC-WR-0019',
  'Round-trip: Global JSON Schemas': 'TC-WR-0018',
  'Round-trip: Linked release ledger': 'TC-WR-0021',
  'Round-trip: Linked request overrides': 'TC-WR-0017',
  'Round-trip: Linked workspaces and overrides': 'TC-WR-0016',
  'Round-trip: Mock endpoint matching rules': 'TC-WR-0014',
  'Round-trip: Mock response bodies and headers': 'TC-WR-0015',
  'Round-trip: Mock servers': 'TC-WR-0013',
  'Round-trip: Plan step enable/disable flags': 'TC-WR-0012',
  'Round-trip: Release ledger entries': 'TC-WR-0020',
  'Round-trip: Request URL/method/headers/body/auth': 'TC-WR-0002',
  'Round-trip: Request docs (Markdown)': 'TC-WR-0004',
  'Round-trip: Request scripts (pre/test) and assertions': 'TC-WR-0003',
  'Round-trip: Request settings (timeout, redirect)': 'TC-WR-0005',
  'Round-trip: Secret keys / slots metadata': 'TC-WR-0023',
  'Round-trip: Secret variables (encrypted at rest)': 'TC-WR-0010',
  'Round-trip: Workspace passphrase metadata': 'TC-WR-0022',
  'Schema version mismatch (newer repo)': 'TC-WR-0026',
  'Schema version mismatch (older repo)': 'TC-WR-0025',
  'Workspace with broken refs (request -> deleted folder)': 'TC-WR-0029',
};
