// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: JS. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapJS: Readonly<Record<string, TcId>> = {
  '$ref to URL (http)': 'TC-JS-0012',
  '$ref with JSON Pointer escapes (~0, ~1)': 'TC-JS-0011',
  'Circular $ref': 'TC-JS-0008',
  'External $ref broken (asset missing)': 'TC-JS-0010',
  'External $ref to file': 'TC-JS-0009',
  'Local $ref at root': 'TC-JS-0001',
  'Local $ref nested 2 levels': 'TC-JS-0002',
  'Local $ref nested 5 levels': 'TC-JS-0003',
  'Local $ref with allOf': 'TC-JS-0004',
  'Local $ref with anyOf': 'TC-JS-0005',
  'Local $ref with not': 'TC-JS-0007',
  'Local $ref with oneOf': 'TC-JS-0006',
  'Schema applied to response body too (if supported)': 'TC-JS-0019',
  'Schema autocomplete in body editor': 'TC-JS-0020',
  'Schema delete with refs warns': 'TC-JS-0023',
  'Schema edit live re-validates body': 'TC-JS-0021',
  'Schema rename updates references': 'TC-JS-0022',
  'Schema validation - missing required field': 'TC-JS-0013',
  'Schema validation - wrong type': 'TC-JS-0014',
  'Schema with enum': 'TC-JS-0016',
  'Schema with min/max length': 'TC-JS-0017',
  'Schema with min/max value (number)': 'TC-JS-0018',
  'Schema with pattern regex': 'TC-JS-0015',
};
