// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.
//
// Module: ME. Maps a sub-feature key (or `sub :: title`
// for collisions) to its TC-ID. Used by Playwright specs to tag
// tests so the coverage report can credit the right rows.

import type { TcId } from './tcCoverage';

export const tcMapME: Readonly<Record<string, TcId>> = {
  Casing: 'TC-ME-0013',
  Custom: 'TC-ME-0014',
  'DELETE :: DELETE with body (e.g., Elasticsearch)': 'TC-ME-0008',
  'DELETE :: DELETE without body': 'TC-ME-0007',
  'GET :: GET with attempted JSON body sent anyway': 'TC-ME-0002',
  'GET :: Send simple GET to echo endpoint': 'TC-ME-0001',
  'HEAD :: HEAD returns headers only': 'TC-ME-0009',
  'HEAD :: HEAD with body configured': 'TC-ME-0010',
  'OPTIONS :: OPTIONS lists allowed methods': 'TC-ME-0011',
  'OPTIONS :: OPTIONS preflight headers shown': 'TC-ME-0012',
  PATCH: 'TC-ME-0006',
  'POST :: POST with empty JSON object': 'TC-ME-0004',
  'POST :: POST with empty body': 'TC-ME-0003',
  PUT: 'TC-ME-0005',
};
