"""Generate canonical TC-ID maps from the manual workbooks for every
module. Output: `e2e/web/fixtures/tcMap<MM|AM|...>.ts` — one map
per module-code. The maps are imported by Playwright specs; the coverage
report (`scripts/e2e_coverage_report.py`) scans them to credit which
TC-IDs each spec covers.

Usage:
  python scripts/build_tc_maps.py

Re-run after editing the workbooks so the maps and tagged tests stay
in lock-step.
"""
from __future__ import annotations
from collections import defaultdict
from pathlib import Path

from openpyxl import load_workbook

REPO = Path(__file__).parent.parent
WEB = REPO / "docs" / "qa" / "web-app-manual-test-cases.xlsx"
DESK = REPO / "docs" / "qa" / "desktop-app-manual-test-cases.xlsx"
OUT_DIR = REPO / "e2e" / "web" / "fixtures"


def safe_key(s: str) -> str:
    return (s or "").replace('"', '\\"')


def collect(path: Path) -> dict[str, dict[str, str]]:
    """Map TC-ID → row (module, sub, type, title, priority)."""
    out: dict[str, dict[str, str]] = {}
    if not path.exists():
        return out
    wb = load_workbook(path, read_only=True)
    ws = wb["Test Cases"]
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row or not row[0]:
            continue
        out[row[0]] = {
            "module": row[1] or "",
            "sub": row[2] or "",
            "type": row[3] or "",
            "title": row[4] or "",
            "priority": row[11] or "",
        }
    return out


def module_code(tc_id: str) -> str:
    """Extract the 2-3 letter module code from a TC-ID like TC-MM-0001."""
    parts = tc_id.split("-")
    return parts[1] if len(parts) >= 3 else "??"


def write_map(code: str, entries: dict[str, dict[str, str]]) -> Path:
    """Emit `tcMap<CODE>.ts` mapping `sub` → TC-ID for the module."""
    out_path = OUT_DIR / f"tcMap{code}.ts"
    # Use sub-feature string as the key. For modules where many rows
    # share the same sub-feature (and would collide), fall back to
    # `sub|title` as a disambiguator.
    by_sub: dict[str, list[str]] = defaultdict(list)
    for tc_id in sorted(entries):
        by_sub[entries[tc_id]["sub"]].append(tc_id)
    mapping: dict[str, str] = {}
    for sub, ids in by_sub.items():
        if len(ids) == 1:
            mapping[sub] = ids[0]
        else:
            # Disambiguate by appending the title where collisions exist.
            for tc_id in ids:
                title = entries[tc_id]["title"]
                key = f"{sub} :: {title}"
                mapping[key] = tc_id

    lines = [
        "// AUTO-GENERATED by scripts/build_tc_maps.py. Do not hand-edit.",
        "//",
        f"// Module: {code}. Maps a sub-feature key (or `sub :: title`",
        "// for collisions) to its TC-ID. Used by Playwright specs to tag",
        "// tests so the coverage report can credit the right rows.",
        "",
        "import type { TcId } from './tcCoverage';",
        "",
        f"export const tcMap{code}: Readonly<Record<string, TcId>> = {{",
    ]
    for key, tc_id in sorted(mapping.items()):
        lines.append(f'  "{safe_key(key)}": "{tc_id}",')
    lines.append("};")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return out_path


def main() -> int:
    web = collect(WEB)
    desk = collect(DESK)
    # Union both workbooks — a TC-ID present in either workbook is in
    # scope for automation.
    all_ids = {**desk, **web}  # web takes precedence on duplicates

    by_code: dict[str, dict[str, dict[str, str]]] = defaultdict(dict)
    for tc_id, row in all_ids.items():
        by_code[module_code(tc_id)][tc_id] = row

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for code, entries in sorted(by_code.items()):
        path = write_map(code, entries)
        written.append((code, len(entries), path))

    for code, n, path in written:
        print(f"  {code:>3}: {n:5d} rows  ->  {path.relative_to(REPO)}")
    print(f"\nTotal: {sum(n for _, n, _ in written)} TC-IDs across {len(written)} modules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
